[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

 [[redirects]]
from = "/api/*"
to = "https://thuctaptotnghiep-production.up.railway.app/:splat"
status = 200
force = true

[[redirects]]
from = "/uploads/*"
to = "https://thuctaptotnghiep-production.up.railway.app/uploads/:splat"
status = 200
force = true
